version: '3.1'

services:
  background-pool:
    # TODO: Please add account & password for the database in .env
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8089:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: 'admin'
      # ME_CONFIG_MONGODB_ADMINPASSWORD: 'pass'
      ME_CONFIG_MONGODB_SERVER: 'background-pool'
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - mongo
    depends_on:
      - background-pool

networks:
  mongo:
    driver: bridge
